CREATE TABLE USERS( ID VARCHAR (128) NOT NULL UNIQUE, EMAIL VARCHAR (89) NOT NULL,
FIRSTNAME VARCHAR (20) NOT NULL, LASTNAME VARCHAR (20), PASSWORD VARCHAR(60) NOT NULL, USERTYPE VARCHAR(20), DESCRIPTION VARCHAR(100), INSTITUTION VARCHAR(100), ENABLED BOOLEAN, PRIMARY KEY (ID));
