package com.loginservice.login.helper;

public enum Errors {
    VALID ("PASSWORD IS VALID"),
    EMPTY ("PASSWORD CANNOT BE EMPTY [NEEDS AT LEAST 1 ALPHABET, 1 NUMBER AND 1 SPECIAL CHARACTER, LENGTH SHOULD BE MINIMUM 7 CHARACTERS]"),
    LAST_NAME_EMPTY ("LAST NAME CANNOT BE EMPTY"),
    FIRST_NAME_EMPTY ("FIRST NAME CANNOT BE EMPTY"),
    PASSWORD_LENGTH ("PASSWORD LENGTH CANNOT BE LESS THAN 7 [NEEDS AT LEAST 1 ALPHABET, 1 NUMBER AND 1 SPECIAL CHARACTER, LENGTH SHOULD BE MINIMUM 7 CHARACTERS]"),
    PASSWORD_VALID_CHARACTERS ("[PASSWORD NEEDS AT LEAST 1 ALPHABET, 1 NUMBER AND 1 SPECIAL CHARACTER, LENGTH SHOULD BE MINIMUM 7 CHARACTERS]"),
    EMAIL_EMPTY ("EMAIL CANNOT BE EMPTY"),
    NO_EXISTING_USER ("USER DOES NOT EXIST"),
    NOT_ENABLED ("USER IS NOT ENABLED YET OR HAS BEEN DISABLED, CONFIRM USER FROM EMAIL"),
    EXISTING_USER ("USER ALREADY EXIST"),
    INCORRECT_PASSWORD ("LOGIN CREDENTIALS INCORRECT"),
    AUTHENTICATED ("AUTHENTICATED"),
    AUTH_TOKEN_INVALID ("AUTH TOKEN INVALID OR ALREADY EXPIRED"),
    AUTH_TOKEN_EMPTY ("AUTH TOKEN EMPTY"),
    CREATED ("CREATED"),
    USER_TYPE_NOT_DEFINED ("USER TYPE NOT DEFINED"),
    DESCRIPTION ("PLEASE DESCRIBE ABOUT YOURSELF, CANNOT BE BLANK"),
    ENABLED ("USER IS ENABLED, PLEASE CHECK EMAIL AND CLICK ON THE CONFIRMATION LINK");




    private String error;

    private Errors(String error) {
        this.error = error ;
    }

    public String getError () {
        return error;
    }
}
